# 应用名称
# spring.application.name=pay
# 应用服务 WEB 访问端口
# server.port=8080
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
# mybatis.mapper-locations=classpath:mappers/*xml
#指定Mybatis的实体目录
# mybatis.type-aliases-package=com.immoc.pay.mybatis.entity
# 数据库驱动：
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 数据源名称
# spring.datasource.name=defaultDataSource
# 数据库连接地址
# spring.datasource.url=jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
# 数据库用户名&密码：
# spring.datasource.username=***
# spring.datasource.password=***

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lqeclh.com2018
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf-8&useSSL=false&severTimezone=Asia/Shanghai
  rabbitmq:
    addresses: 192.168.157.128
    port: 15672
    username: guest
    password: guest

#logging:
#  pattern:
#    console: "[%thread] %-5level %logger{36} - %msg%n"

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml

wx:
  appId: wx3e6b9f1c5a7ff034
  mchId: 1614433647
  mchKey: Aa111111111122222222223333333333
  notifyUrl: http://haogege-mall.natapp1.cc/pay/notify
  returnUrl: http://127.0.0.1

server:
  port: 8083
